spring:
  profiles:
    active:
      -dev
---
spring:
  profiles: dev  #开发环境
  application:
    name: springcloud-config-zhu-dev
---
spring:
  profiles: test  #测试环境
  application:
    name: springcloud-config-zhu-test
#必须保存utf-8格式